version: '3.3'
services: 
    db: 
        image: mysql:latest 
        container_name: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_USER: changeme
            MYSQL_PASSWORD: changeme
        ports: 
            - 6004:3306
    web:
        image:  elki97413/pdo_mysql-php-apache:1.0.1
        container_name: pma-apache-php8
        depends_on: 
            - db
        volumes: 
            - ./php:/var/www/html
        restart: always
        environment: 
             - PMA_HOST=db
             - PMA_ARBITRATY=1
        ports: 
            - 80:80