version: '3.3'
services: 
    web:
        image:  elki97413/pdo_mysql-php-apache
        container_name: apache-php
        depends_on: 
            - db
        volumes: 
            - ./php:/var/www/html
        restart: always
        ports: 
            - 80:80
    db: 
        image: mysql:latest 
        container_name: server_mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: 2020
        ports: 
            - 6003:3306
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        environment: 
            - PMA_ARBITRATY=1
        restart: always
        ports:
            - 8080:80
        volumes: 
            - ./phpmyadmin/theme/:/www/themes/theme/